### ISSUE TITLE
Unknown command line input for 2d use

### ISSUE THREAD

**Issue by schoeller** [Giswater/giswater_water_models#1]
Dear all,

thanks for letting me use your software.

I have the following setup in order to test out 2d capabilities all setup in the same directory

1.Export from the ud-example from Giswater is stored as temp.inp

2.swmm51006_2d.exe executed on the command returns
`swmm5 <input file> <report file> <output file>`

3.Executing the command
`swmm51006_2d.exe temp.inp temp.rpt temp.out`
returns the message
`'ERROR: Cannot open input file (.\topo.txt).'`

4.The raster file from Giswater installation directory samples/topo.asc is copied to topo.txt and swmm is called which returns
`'... EPA-SWMM completed in 0.00 seconds. There are errors.'`

5.The temp.rpt file reads
`'EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.1.005)`
`  --------------------------------------------------------------`
`  ERROR 205: invalid keyword  at line 599 of input file:`
`  [GWF]`
`  ERROR 205: invalid keyword  at line 1496 of input file:`
`  [ADJUSTMENTS]`
`  Analysis begun on:  Sat May 12 10:40:27 2018`
`  Analysis ended on:  Sat May 12 10:40:27 2018`
`  Total elapsed time: < 1 sec`

This to me is an unrelated error.

Please elaborate what raster input format to use for topo.txt. I cannot read it from the source code.

Best regards

Sebastian

**Comment by schoeller** [comment]
Using Saga I converted the original topo.asc into Arc ASCII format. The file header from topo.txt now reads like this

`NCOLS 2058
NROWS 2043
XLLCORNER 414705.0544640120
YLLCORNER 4570181.7408444630
CELLSIZE 4.999951
NODATA_VALUE -99999.0000`

When running the command I receive a different output
`... EPA-SWMM completed in 6.00 seconds. There are errors.`

No out-file is generated. The file rpt reads like this

`  EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.1.005)`
`  -------------------------------------------------------------- `
`  ERROR 205: invalid keyword  at line 599 of input file:`
`  [GWF]`
`  ERROR 205: invalid keyword  at line 1496 of input file:`
`  [ADJUSTMENTS]`
`  Analysis begun on:  Sat May 12 11:19:44 2018`
`  Analysis ended on:  Sat May 12 11:19:50 2018`
`  Total elapsed time: 00:00:06`

This still looks to me like an unrelated error

**Comment by vicente-medina** [comment]
Dear Sebastian, I think it has nothing to do with the topo raster. The error you get seems to be related to the INP file, in fact it says that SWMM is finding unknown statements in the input file. It usually occours if you are running an INP from a different SWMM version.

Probably the example you are running from the giswater package includes features that doesn't exist in the 2D SWMM version.

In fact if you read the SWMM updates file:

https://www.epa.gov/sites/production/files/2017-03/epaswmm5_updates_0.txt

you can see that the [GWF] was introduced in the 5.1.007 and the 2D is based in the 005/006 (I'm not sure). Therefore it is normal that the example does not run in the 2D.

On the other hand, I think that the example miss some information to be sure that it runs as 2D. In the INP you should include the subcatchments geometry, there is an specific checkbox to do it, by default the INP does not include the subcatchments geometry because it requires a lot of disk space.

Additionally the name of the subcatchments should start with an "s" letter to indicate that the polygon is "street" and it must be included in the 2D mesh.

As you have discovered the topo must be included as "topo.txt" file, probably in the example you are running the nodes, pipes and subcatchments coordinates are not within the topo domain.

Probably the best choice fo you is create your network, reun it in the SWMM and once you are able to run it add the extra data to run it in the 2D.

The conversion requires you to have a DTM (digital terrain model) of the area. Start identifying all the subcatchments as "s" and try to run the 2D SWMM (selecting it in the GISWATER model box).

Once it runs you should improve the mesh, separating roof polygons and street polygons, only the street ones must keep the "s" starting letter, hence the model is able to construct the computational mesh using the "street" polygons only.
